version: '3.4'

networks:
  identityapiapp:

services:
  db:
    container_name: identity-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1235#
    volumes:
       - ./sqlserver/data:/var/opt/mssql/data
       - ./sqlserver/log:/var/opt/mssql/log
    networks:
      - identityapiapp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1433"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 5s

  identityapi:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi/Dockerfile
    ports:
      - 8001:80
    depends_on:
       db:
        condition: service_started
    networks:
      - identityapiapp
