version: '3.4'

networks:
  identityapiapp:

services:
  db:
    container_name: identity-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1235#
    volumes:
       - ./sqlserver/data:/var/opt/mssql/data
    networks:
      - identityapiapp

  identityapi:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi/Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=IdentityService;User Id=sa;Password=Password@1235#;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - identityapiapp
