version: '3.4'

networks:
  socialmediaapp:

services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1235#
    volumes:
       - ./sqlserver/data:/var/opt/mssql/data
    networks:
      - socialmediaapp

  identityapi:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=IdentityService;User Id=sa;Password=Password@1235#;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - socialmediaapp

  postapi:
    container_name: post-api
    image: ${DOCKER_REGISTRY-}postapi
    build:
      context: .
      dockerfile: PostApi/Dockerfile
    ports:
      - "5134:5134"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PostService;User Id=sa;Password=Password@1235#;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - socialmediaapp

  peopleapi:
    container_name: people-api
    image: ${DOCKER_REGISTRY-}peopleapi
    build:
      context: .
      dockerfile: PeopleApi/Dockerfile
    ports:
      - "5030:5030"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PeopleService;User Id=sa;Password=Password@1235#;TrustServerCertificate=True;
    depends_on:
      - sqlserver
    networks:
      - socialmediaapp

  blazorapp:
    container_name: frontend
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: .
      dockerfile: FrontendApp/Dockerfile
    ports:
      - "5159:5159"
    depends_on:
      - sqlserver
      - identityapi
      - postapi
      - peopleapi
    networks:
      - socialmediaapp
