version: '3.4'

networks: 
    identityapiapp:

services:
  db:
    container_name: identity-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 8002:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password@1235#
  identityapi:
    container_name: identity-api
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: IdentityApi/Dockerfile
    ports:
      - 8001:80
    depends_on:
      - db
    networks: 
      - identityapiapp